CREATE TABLE IF NOT EXISTS `kqde_items` (
  `identifier` VARCHAR(64) NOT NULL,
  `item` VARCHAR(64) NOT NULL,
  `amount` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`identifier`,`item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kqde_wallets` (
  `identifier` VARCHAR(64) NOT NULL PRIMARY KEY,
  `cash` BIGINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kqde_wallet_flags` (
  `identifier` VARCHAR(64) NOT NULL PRIMARY KEY,
  `used_setcash` TINYINT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kqde_lockers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `x` DOUBLE NOT NULL,
  `y` DOUBLE NOT NULL,
  `z` DOUBLE NOT NULL,
  `heading` DOUBLE NOT NULL DEFAULT 0,
  `cash` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `kqde_locker_items` (
  `locker_id` INT NOT NULL,
  `item` VARCHAR(64) NOT NULL,
  `amount` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`locker_id`,`item`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
